name: CI-build-and-push-image-for-Shop-FE

# Controls when the action will run.
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      - '**/.dockerignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      - '**/.dockerignore'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Thêm bước cài đặt Node.js và npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopview:latest, ${{ secrets.DOCKERHUB_USERNAME }}/shopview:${{ github.run_number }}
